//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// Исходное имя файла:
// Дата создания: 19.02.2017 13:06:33
namespace DomainModel.WMSDatabaseService
{
    
    /// <summary>
    /// В схеме отсутствуют комментарии для WMSEntities.
    /// </summary>
    public partial class WMSEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Инициализируйте новый объект WMSEntities.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public WMSEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Поскольку пространство имен, настроенное для этой ссылки на службу
        /// в Visual Studio, отличается от пространства имен, указанного
        /// в схеме сервера, для сопоставления этих пространств имен используйте преобразователи типов.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "WMSModel", "DomainModel.WMSDatabaseService");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Поскольку пространство имен, настроенное для этой ссылки на службу
        /// в Visual Studio, отличается от пространства имен, указанного
        /// в схеме сервера, для сопоставления этих пространств имен используйте преобразователи типов.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("DomainModel.WMSDatabaseService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("WMSModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// В схеме отсутствуют комментарии для Data.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Data> Data
        {
            get
            {
                if ((this._Data == null))
                {
                    this._Data = base.CreateQuery<Data>("Data");
                }
                return this._Data;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Data> _Data;
        /// <summary>
        /// В схеме отсутствуют комментарии для Sensors.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Sensor> Sensors
        {
            get
            {
                if ((this._Sensors == null))
                {
                    this._Sensors = base.CreateQuery<Sensor>("Sensors");
                }
                return this._Sensors;
            }
        }

        public object Entry { get; internal set; }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Sensor> _Sensors;
        /// <summary>
        /// В схеме отсутствуют комментарии для Data.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToData(Data data)
        {
            base.AddObject("Data", data);
        }
        /// <summary>
        /// В схеме отсутствуют комментарии для Sensors.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSensors(Sensor sensor)
        {
            base.AddObject("Sensors", sensor);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"WMSModel\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\"><Entit" +
                "yType Name=\"Data\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"" +
                "Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http:/" +
                "/schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"SensorId\" T" +
                "ype=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Date\" Type=\"Edm.DateTime\" Nul" +
                "lable=\"false\" Precision=\"0\" /><Property Name=\"Time\" Type=\"Edm.Time\" Nullable=\"fa" +
                "lse\" Precision=\"7\" /><Property Name=\"Value\" Type=\"Edm.Int32\" Nullable=\"false\" />" +
                "<NavigationProperty Name=\"Sensors\" Relationship=\"WMSModel.FK_Data_Sensor\" ToRole" +
                "=\"Sensors\" FromRole=\"Data\" /></EntityType><EntityType Name=\"Sensor\"><Key><Proper" +
                "tyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" p6" +
                ":StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://schemas.microsoft.com/ado/200" +
                "9/02/edm/annotation\" /><Property Name=\"Name\" Type=\"Edm.String\" Nullable=\"false\" " +
                "MaxLength=\"50\" FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"SensorType\"" +
                " Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"" +
                "false\" /><Property Name=\"Lat\" Type=\"Edm.Double\" Nullable=\"false\" /><Property Nam" +
                "e=\"Lng\" Type=\"Edm.Double\" Nullable=\"false\" /><Property Name=\"Radius\" Type=\"Edm.I" +
                "nt32\" Nullable=\"false\" /><NavigationProperty Name=\"Data\" Relationship=\"WMSModel." +
                "FK_Data_Sensor\" ToRole=\"Data\" FromRole=\"Sensors\" /></EntityType><Association Nam" +
                "e=\"FK_Data_Sensor\"><End Type=\"WMSModel.Sensor\" Role=\"Sensors\" Multiplicity=\"1\" /" +
                "><End Type=\"WMSModel.Data\" Role=\"Data\" Multiplicity=\"*\" /><ReferentialConstraint" +
                "><Principal Role=\"Sensors\"><PropertyRef Name=\"Id\" /></Principal><Dependent Role=" +
                "\"Data\"><PropertyRef Name=\"SensorId\" /></Dependent></ReferentialConstraint></Asso" +
                "ciation></Schema><Schema Namespace=\"WMSDataService\" xmlns=\"http://schemas.micros" +
                "oft.com/ado/2009/11/edm\"><EntityContainer Name=\"WMSEntities\" m:IsDefaultEntityCo" +
                "ntainer=\"true\"><EntitySet Name=\"Data\" EntityType=\"WMSModel.Data\" /><EntitySet Na" +
                "me=\"Sensors\" EntityType=\"WMSModel.Sensor\" /><AssociationSet Name=\"FK_Data_Sensor" +
                "\" Association=\"WMSModel.FK_Data_Sensor\"><End Role=\"Data\" EntitySet=\"Data\" /><End" +
                " Role=\"Sensors\" EntitySet=\"Sensors\" /></AssociationSet></EntityContainer></Schem" +
                "a></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// В схеме отсутствуют комментарии для WMSModel.Data.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Data")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Data : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Создайте новый объект Data.
        /// </summary>
        /// <param name="ID">Начальное значение Id.</param>
        /// <param name="sensorId">Начальное значение SensorId.</param>
        /// <param name="date">Начальное значение Date.</param>
        /// <param name="time">Начальное значение Time.</param>
        /// <param name="value">Начальное значение Value.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Data CreateData(int ID, int sensorId, global::System.DateTime date, global::System.TimeSpan time, int value)
        {
            Data data = new Data();
            data.Id = ID;
            data.SensorId = sensorId;
            data.Date = date;
            data.Time = time;
            data.Value = value;
            return data;
        }
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Id.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства SensorId.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SensorId
        {
            get
            {
                return this._SensorId;
            }
            set
            {
                this.OnSensorIdChanging(value);
                this._SensorId = value;
                this.OnSensorIdChanged();
                this.OnPropertyChanged("SensorId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SensorId;
        partial void OnSensorIdChanging(int value);
        partial void OnSensorIdChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Date.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this._Date = value;
                this.OnDateChanged();
                this.OnPropertyChanged("Date");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Time.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.TimeSpan Time
        {
            get
            {
                return this._Time;
            }
            set
            {
                this.OnTimeChanging(value);
                this._Time = value;
                this.OnTimeChanged();
                this.OnPropertyChanged("Time");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.TimeSpan _Time;
        partial void OnTimeChanging(global::System.TimeSpan value);
        partial void OnTimeChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Value.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this._Value = value;
                this.OnValueChanged();
                this.OnPropertyChanged("Value");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Value;
        partial void OnValueChanging(int value);
        partial void OnValueChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для Sensors.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Sensor Sensors
        {
            get
            {
                return this._Sensors;
            }
            set
            {
                this._Sensors = value;
                this.OnPropertyChanged("Sensors");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Sensor _Sensors;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// В схеме отсутствуют комментарии для WMSModel.Sensor.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Sensors")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Sensor : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Создайте новый объект Sensor.
        /// </summary>
        /// <param name="ID">Начальное значение Id.</param>
        /// <param name="name">Начальное значение Name.</param>
        /// <param name="sensorType">Начальное значение SensorType.</param>
        /// <param name="lat">Начальное значение Lat.</param>
        /// <param name="lng">Начальное значение Lng.</param>
        /// <param name="radius">Начальное значение Radius.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Sensor CreateSensor(int ID, string name, string sensorType, double lat, double lng, int radius)
        {
            Sensor sensor = new Sensor();
            sensor.Id = ID;
            sensor.Name = name;
            sensor.SensorType = sensorType;
            sensor.Lat = lat;
            sensor.Lng = lng;
            sensor.Radius = radius;
            return sensor;
        }
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Id.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Name.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства SensorType.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SensorType
        {
            get
            {
                return this._SensorType;
            }
            set
            {
                this.OnSensorTypeChanging(value);
                this._SensorType = value;
                this.OnSensorTypeChanged();
                this.OnPropertyChanged("SensorType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SensorType;
        partial void OnSensorTypeChanging(string value);
        partial void OnSensorTypeChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Lat.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double Lat
        {
            get
            {
                return this._Lat;
            }
            set
            {
                this.OnLatChanging(value);
                this._Lat = value;
                this.OnLatChanged();
                this.OnPropertyChanged("Lat");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _Lat;
        partial void OnLatChanging(double value);
        partial void OnLatChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Lng.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double Lng
        {
            get
            {
                return this._Lng;
            }
            set
            {
                this.OnLngChanging(value);
                this._Lng = value;
                this.OnLngChanged();
                this.OnPropertyChanged("Lng");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _Lng;
        partial void OnLngChanging(double value);
        partial void OnLngChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Radius.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Radius
        {
            get
            {
                return this._Radius;
            }
            set
            {
                this.OnRadiusChanging(value);
                this._Radius = value;
                this.OnRadiusChanged();
                this.OnPropertyChanged("Radius");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Radius;
        partial void OnRadiusChanging(int value);
        partial void OnRadiusChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для Data.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Data> Data
        {
            get
            {
                return this._Data;
            }
            set
            {
                this._Data = value;
                this.OnPropertyChanged("Data");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Data> _Data = new global::System.Data.Services.Client.DataServiceCollection<Data>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
