//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Values
    {
        public int ID { get; set; }
        public int SensorID { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public double Value { get; set; }
    
        public virtual Sensors Sensor { get; set; }
    }
}
